<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Valitron\\' => array($vendorDir . '/vlucas/valitron/src/Valitron'),
    'Laminas\\Stdlib\\' => array($vendorDir . '/laminas/laminas-stdlib/src'),
    'Laminas\\Db\\' => array($vendorDir . '/laminas/laminas-db/src'),
);
